import {
  LayoutDashboard,
  Building2,
  Package,
  MapPin,
  Boxes,
  DollarSign,
  FileText,
  Truck,
  Receipt,
  ClipboardCheck,
  ClipboardList,
  Settings,
  Shield,
  AlertTriangle,
  FileSearch,
  BarChart3,
  BookOpen,
  Calculator,
  PieChart,
  Calendar,
  CreditCard,
  Clock,
  Users,
  ArrowDownToLine,
  FileX,
  Landmark,
  ArrowRightLeft,
  TrendingUp,
  Scale,
  FolderKanban,
  ShoppingCart,
  FileCheck,
  Percent,
  BookOpenCheck,
  PackageMinus,
  Bell,
} from 'lucide-react';

// Map each nav path to a program code in the permissions table
export const pathToProgram: Record<string, string> = {
  '/': 'dashboard',
  '/vendor-dashboard': 'vendor_dashboard',
  '/procurement-dashboard': 'procurement_dashboard',
  '/warehouse-dashboard': 'warehouse_dashboard',
  '/finance-dashboard': 'finance_dashboard',
  '/sales-dashboard': 'sales_dashboard',
  '/cash-dashboard': 'cash_dashboard',
  '/vendors': 'vendors',
  '/vendor-performance': 'vendor_performance',
  '/rfps': 'rfps',
  '/items': 'items',
  '/locations': 'locations',
  '/requisitions': 'requisitions',
  '/purchase-orders': 'purchase_orders',
  '/inventory': 'inventory',
  '/inventory-valuation': 'inventory_valuation',
  '/inventory-issues': 'inventory_issues',
  '/goods-receipts': 'goods_receipts',
  '/chart-of-accounts': 'chart_of_accounts',
  '/journal-entries': 'journal_entries',
  '/financial-reports': 'financial_reports',
  '/fiscal-periods': 'fiscal_periods',
  '/audit-report': 'financial_reports',
  '/account-statement': 'financial_reports',
  '/invoices': 'invoices',
  '/ap-payments': 'ap_payments',
  '/ap-aging': 'ap_aging',
  '/match-exceptions': 'match_exceptions',
  '/customers': 'customers',
  '/ar-invoices': 'ar_invoices',
  '/ar-receipts': 'ar_receipts',
  '/ar-credit-notes': 'ar_credit_notes',
  '/ar-aging': 'ar_aging',
  '/bank-accounts': 'bank_accounts',
  '/fund-transfers': 'fund_transfers',
  '/bank-reconciliation': 'bank_reconciliation',
  '/cash-flow-forecast': 'cash_flow_forecast',
  '/projects': 'projects',
  '/project-profitability': 'project_profitability',
  '/po-closure': 'po_closure',
  '/procurement-reports': 'procurement_reports',
  '/warehouse-reports': 'warehouse_reports',
  '/ap-reports': 'ap_reports',
  '/ar-reports': 'ar_reports',
  '/cash-reports': 'cash_reports',
  '/tax-configuration': 'tax_configuration',
  '/sales-quotations': 'sales_quotations',
  '/sales-orders': 'sales_orders',
  '/delivery-notes': 'delivery_notes',
  '/notifications': 'notifications',
  '/approval-rules': 'approval_rules',
  '/user-management': 'user_management',
  '/admin': 'admin',
};

export const navSections = [
  {
    label: 'Main',
    items: [
      { path: '/', label: 'Dashboard', icon: LayoutDashboard },
    ],
  },
  {
    label: 'Dashboards',
    items: [
      { path: '/vendor-dashboard', label: 'Vendor Mgmt', icon: Building2 },
      { path: '/procurement-dashboard', label: 'Procurement', icon: FileText },
      { path: '/warehouse-dashboard', label: 'Warehouse', icon: Boxes },
      { path: '/finance-dashboard', label: 'Finance', icon: Calculator },
      { path: '/sales-dashboard', label: 'Sales', icon: ShoppingCart },
      { path: '/cash-dashboard', label: 'Cash Mgmt', icon: Landmark },
    ],
  },
  {
    label: 'Procurement',
    items: [
      { path: '/vendors', label: 'Vendors', icon: Building2 },
      { path: '/vendor-performance', label: 'Vendor Performance', icon: BarChart3 },
      { path: '/rfps', label: 'Requests for Proposal', icon: FileSearch },
      { path: '/items', label: 'Items', icon: Package },
      { path: '/locations', label: 'Locations', icon: MapPin },
      { path: '/requisitions', label: 'Requisitions', icon: ClipboardList },
      { path: '/purchase-orders', label: 'Purchase Orders', icon: FileText },
    ],
  },
  {
    label: 'Warehouse',
    items: [
      { path: '/inventory', label: 'Inventory', icon: Boxes },
      { path: '/inventory-valuation', label: 'Inventory Valuation', icon: DollarSign },
      { path: '/inventory-issues', label: 'Inventory Issues', icon: PackageMinus },
      { path: '/goods-receipts', label: 'Goods Receipts', icon: Truck },
    ],
  },
  {
    label: 'General Ledger',
    items: [
      { path: '/chart-of-accounts', label: 'Chart of Accounts', icon: BookOpen },
      { path: '/journal-entries', label: 'Journal Entries', icon: Calculator },
      { path: '/financial-reports', label: 'Financial Reports', icon: PieChart },
      { path: '/fiscal-periods', label: 'Fiscal Periods', icon: Calendar },
      { path: '/audit-report', label: 'Audit Report', icon: FileSearch },
      { path: '/account-statement', label: 'Statement of Account', icon: FileText },
    ],
  },
  {
    label: 'Finance - AP',
    items: [
      { path: '/invoices', label: 'AP Invoices', icon: Receipt },
      { path: '/ap-payments', label: 'AP Payments', icon: CreditCard },
      { path: '/ap-aging', label: 'AP Aging', icon: Clock },
      { path: '/match-exceptions', label: 'Match Exceptions', icon: AlertTriangle },
    ],
  },
  {
    label: 'Finance - AR',
    items: [
      { path: '/customers', label: 'Customers', icon: Users },
      { path: '/ar-invoices', label: 'AR Invoices', icon: Receipt },
      { path: '/ar-receipts', label: 'AR Receipts', icon: ArrowDownToLine },
      { path: '/ar-credit-notes', label: 'Credit Notes', icon: FileX },
      { path: '/ar-aging', label: 'AR Aging', icon: Clock },
    ],
  },
  {
    label: 'Sales',
    items: [
      { path: '/sales-quotations', label: 'Quotations', icon: FileCheck },
      { path: '/sales-orders', label: 'Sales Orders', icon: ShoppingCart },
      { path: '/delivery-notes', label: 'Delivery Notes', icon: Truck },
    ],
  },
  {
    label: 'Cash Management',
    items: [
      { path: '/bank-accounts', label: 'Bank Accounts', icon: Landmark },
      { path: '/fund-transfers', label: 'Fund Transfers', icon: ArrowRightLeft },
      { path: '/bank-reconciliation', label: 'Reconciliation', icon: Scale },
      { path: '/cash-flow-forecast', label: 'Cash Forecast', icon: TrendingUp },
    ],
  },
  {
    label: 'Project Accounting',
    items: [
      { path: '/projects', label: 'Projects', icon: FolderKanban },
      { path: '/project-profitability', label: 'Profitability', icon: TrendingUp },
    ],
  },
  {
    label: 'Reports',
    items: [
      { path: '/procurement-reports', label: 'Procurement Reports', icon: BarChart3 },
      { path: '/warehouse-reports', label: 'Warehouse Reports', icon: BarChart3 },
      { path: '/ap-reports', label: 'AP Reports', icon: BarChart3 },
      { path: '/ar-reports', label: 'AR Reports', icon: BarChart3 },
      { path: '/cash-reports', label: 'Cash Reports', icon: BarChart3 },
      { path: '/po-closure', label: 'PO Closure Report', icon: ClipboardCheck },
    ],
  },
  {
    label: 'Administration',
    items: [
      { path: '/tax-configuration', label: 'Tax Configuration', icon: Percent },
      { path: '/notifications', label: 'Notifications', icon: Bell },
      { path: '/approval-rules', label: 'Approval Rules', icon: Shield },
      { path: '/user-management', label: 'User Management', icon: Shield },
      { path: '/admin', label: 'Admin', icon: Settings },
      { path: '/user-guide', label: 'User Guide', icon: BookOpenCheck },
    ],
  },
];
